### ISSUE TITLE
[BUG] Cannot maxout volume when headphones are plugged in

### ISSUE THREAD

**Issue by igglasty** [ananjaser1211/hadesRom_Reports#106]
**Describe the bug**
Cannot maxout volume when headphones are plugged in. Volume statusbar is working until i reach the orange zone. When on orange zone volume does not change, and i can't make it stay on orange zone - **i turned off volume safety feature and it does not seem to fix it.
**To Reproduce**
1. Listen to something via headphones
2. Volume up unti phone vibrates, go further
3. Volume is high as far as "blue" level on volume statusbar can go

**Expected behavior**
I expect it to work as usual. 

**Smartphone (please complete the following information):**
Regular european exynos Galaxy Note 8 N950F

**Comment by igglasty** [comment]
** i don't have any music/sound mods installed

**Comment by ananjaser1211** [comment]
This will be fixed in the next release 2.1

For a temporary workaround follow this

using fx explorer (or any working file explorer that edits root files)

go to system/odm/etc/omc/YOUR_COUNTRY/conf

edit the file cscfeature.xml

set the line CscFeature_Audio_SupportSafeMediaVolumeDialog to FALSE

Your country can be found in settings > about phone > software info > service provider sw information 

XSG/XSG,XSG/KTC for example means I will edit the XSG folder.

**Comment by Kashev824** [comment]
I can't edit the file. How can I edit it?

**Comment by workonfire** [comment]
> I can't edit the file. How can I edit it?

I edited the file using `nano` in OrangeFox Recovery, because my phone is not rooted.

**Comment by revoltidilo** [comment]
What version of OrangeFox Recovery did you use for the Samsung Galaxy Note 8 (sm-n950f)?

**Comment by workonfire** [comment]
Oh. I have the S8+. I don't know about Note 8 unfortunately.

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
