### ISSUE TITLE
[BUG] HDR and Widevine doesn't work S8

### ISSUE THREAD

**Issue by M4th12** [ananjaser1211/hadesRom_Reports#110]
When you watch a video on YouTube or a streaming service, the HDR is not recognized and the contents are reproduced in SDR (In YouTube, the indication HDR does not even appear on the various resolutions of the video)

**To Reproduce**
1. Go to Youtube
2. Start a video with HDR
3. HDR does not appear in front of the resolutions in the video quality menu.

**Expected behavior**
When a video starts, HDR option doesn't appear

**Screenshots**
![Screenshot_20210926-130556_YouTube](https://user-images.githubusercontent.com/89078127/134805486-27bc60f7-1033-49c2-834f-bd09374a8c25.jpg)
![Screenshot_20210926-130540_DRM Info](https://user-images.githubusercontent.com/89078127/134805487-4515ae29-2e46-43a7-bc9f-fc6db0641ac2.jpg)

**Smartphone
 - Device: Galaxy S8
 - Model: G950F

**Comment by corsicanu** [comment]
@M4th12 To start with i must say you will never achieve L1 while bootloader unlocked/phone rooted, no matter the rom you are running, only way to get L1 back is stock fw, unrooted, oem locked.

As for HDR we did some debug on it and couldn't achieve back that option, most likely because of its port nature, graphics being behind whatever HDR playback needs in Android 10. 

The conclusions - these 2 will never be fixed for various reasons - read me above. 
Regards

**Comment by M4th12** [comment]
Ok thanks for the replay. However great job for this custom rom, it is even faster than the stock one
