### ISSUE TITLE
[BUG]5GHz WiFi signal is low

### ISSUE THREAD

**Issue by audok** [ananjaser1211/hadesRom_Reports#123]
**Describe the bug**
At the same location, the signal strength of 5GHz Wi-Fi is very weak compared to 2.4GHz Wi-Fi.

When I used stockroom, I could use 5GHz WiFi smoothly in my room.(Of course, other devices are the same)
However, in hadesrom, the signal strength is so weak that I can't even connect 5 GHz WiFi in my room.

**Screenshots**
![2 4GHz-21dBm](https://user-images.githubusercontent.com/81354705/149916574-109c042b-411a-470c-8829-11718404750c.jpg)
(↑ 2.4GHz-21dBm)

![5GHz-48dBm](https://user-images.githubusercontent.com/81354705/149916585-b34329b5-2854-49be-9640-3c5e910885a9.jpg)
(↑ 5GHz-48dBm)

**Smartphone (please complete the following information):**
 - Device: Galaxy S8
 - Model: G950N(Korea)

**Comment by AnyCubical** [comment]
Isn't it normal for a 5Ghz WiFi signal being weaker than a 2.4GHz WiFi signal? Unless standing near the WiFi router with no walls or similar thing blocking the sight this is should be a completly normal behaviour. Higher frequencies have a lower range.

**Comment by audok** [comment]
I'm sorry. I didn't write down the details.

When I used stockroom, I could use 5GHz WiFi smoothly in my room.(Of course, other devices are the same)
However, in hadesrom, the signal strength is so weak that I can't even connect 5 GHz WiFi in my room.

**Comment by royoky** [comment]
I have exactly the same issue with the same model (S8 SM-G950N) that someone gave me. But this issue is not present on my Note 8 (SM-N950F), so it could come from this particular S8 model.

**Comment by ananjaser1211** [comment]
Personally on my N950N (korean model) i have not felt a difference between 5G on Stock and ported ROM, since we basically use the stock driver, however it may be possible that korean WiFi firmware is using different TX rating (common usually but most international wifi firmwares are set to max TX rating, while few countries have it reduced either to cut strength or reduce available channels, god knows why). 

since both you and royoky are using G950N ill download the firmware and check, if thats the case i can add a check in the ROM to install a seperate wifi firmware for them.

**Comment by audok** [comment]
Thank you so much for your care.
If this problem is solved, it will be perfect Rom!

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
