### ISSUE TITLE
[BUG] Bixby Routines crashes

### ISSUE THREAD

**Issue by ACardAttack** [ananjaser1211/hadesRom_Reports#24]
[logcat_12-31-2020_09-23-46.txt](https://github.com/ananjaser1211/hadesRom_Reports/files/5757468/logcat_12-31-2020_09-23-46.txt)

This is my first time pulling a logcat, hope I did it right

Routines did work at first, I was able to create a couple, I can add the "IF" statements not problem, but when I hit the plus button to add a "Then" it crashes out of the add routine and takes me back to my routines.  I've wiped data, cache, rebooted, not luck.

Thanks

**Comment by corsicanu** [comment]
According to your log the issue happens because of a database downgrade which only happens when you delete the updated app manually or dirty flash of other mods like oneui 3.0 apps and other crap so i need more info on this. 
For example what's your setup? Did you dirty flash P to Q? Did you update Routines to latest from Galaxy Store? Did you flash anything else than the rom? If yes, what? Using any magisk modules? If yes, which?

You can simply fix it by clearing app data of Routines, but i rather treat the cause not the effect.

**Comment by ACardAttack** [comment]
I did not dirty flash, clean flash.  I might have updated it from the
Galaxy store.  It was working originally.

The only module I have installed is Blobmoji

I have tried cleaning app data, but it doesnt work.

**Comment by AlexandreHertzog** [comment]
I can confirm this happens to me as well. On the first time, I dirty flashed Q over P and that happened some time after usage.

Today I clean installed Q (after formatting system, data, storage) and noticed that it began to happen after Galaxy Store updated the outdated apps.

The existing routines are executing without problems, the crash only happens when starting the "when" activity.

**Comment by SypeR54** [comment]
@AlexandreHertzog Can you provide logs? Log-error.bat should be enough

**Comment by AlexandreHertzog** [comment]
I'll be able to collect the logs when I get to a PC on Tuesday. I'll keep you posted. 

To add, I tried to update manually by downloading the latest version of the Routines app from APK mirror without success.

**Comment by SypeR54** [comment]
@AlexandreHertzog Thank you.

For manually installation, sometimes Package Manager cant install it manually. Can you try to replace it from "system/system/priv-app/Routines"  ?

**Comment by AlexandreHertzog** [comment]
> For manually installation, sometimes Package Manager cant install it manually. Can you try to replace it from "system/system/priv-app/Routines" ?

I definitely try that. I'll let you know the result of this test by tomorrow!

Here's the logs of the crash on a error level: [log_e_routines_crash.log](https://github.com/ananjaser1211/hadesRom_Reports/files/5770503/log_e_routines_crash.log)

I've made 3 tries to edit the `THEN` blocks which triggered the crash, two right after each other at about 10:45 and a third one at around 10:48.

**Comment by lucf15** [comment]
I've replaced the APK in /system/priv-app/Routines with the latest version [3.1.07.2](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/bixby-routines/bixby-routines-3-1-07-2-release/)  found on APKMirror and it never crashed to me with simple routines.

**Comment by ACardAttack** [comment]
> I've replaced the APK in /system/priv-app/Routines with the latest version [3.1.07.2](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/bixby-routines/bixby-routines-3-1-07-2-release/) found on APKMirror and it never crashed to me with simple routines.

I did this, it did fix it, but it's a different Routines, the UI is different and some options aren't present.  I cannot  select change to medium power saving 

I've also gone from the ROM's download and grabbed it's apk and permissions and it didnt fix it either.

**Comment by alianB-R** [comment]
> > I've replaced the APK in /system/priv-app/Routines with the latest version [3.1.07.2](https://www.apkmirror.com/apk/samsung-electronics-co-ltd/bixby-routines/bixby-routines-3-1-07-2-release/) found on APKMirror and it never crashed to me with simple routines.
> 
> I did this, it did fix it, but it's a different Routines, the UI is different and some options aren't present. I cannot select change to medium power saving
> 
> I've also gone from the ROM's download and grabbed it's apk and permissions and it didnt fix it either.

Same issue for Routines, I did this too and for example it crashes when choosing brightness
