### ISSUE TITLE
[BUG] Flash shortcut crashing the system.

### ISSUE THREAD

**Issue by Hidden-Help** [ananjaser1211/hadesRom_Reports#59]
**Describe the bug**
As title says. But the only reason I'm reporting this is if it may help you find something missing for flashlight in future. It's not something everyone uses anyways.

**To Reproduce**
1. Go to settings, lock screen, shortcuts.
2. Add flashlight as a shortcut for lock screen.
3. Lock the phone.
4. Swipe on the flashlight shortcut to bring it up.
5. Everything goes black.

**Expected behavior**
flash to work or whatever but as I said it's not a big problem. I'm just hoping it may help with something.

**Smartphone (please complete the following information):**
 - Device: [note 8]
 - Model: [N950FD]

**Additional context**
I'll gather logs if it's not reproducible. As I'm really just trying to help and not complain or anything. 

With love.

**Comment by ananjaser1211** [comment]
This has to do with #5 , only the qs toggle and camera will run flash light system wise, shortcuts. edge panel (sos stuff) etc will not work and possibly crash.

this is unlikely to be ever fixed

**Comment by lucf15** [comment]
The flashlight level doesn't work as `CameraService` gives this error "Camera 0 has no flashlight" but I've patched the `SystemUI.apk` so that flashlight shortcut from lockscreen works.

Basically the shortcut when pressed triggers the `FlashlightControllerImpl.setFlashlightLevel` method which invokes `this.mCameraManager.setTorchMode` with 3 arguments, the last argument is the level but this method has also a overload with two parameters that enables flashlight without specifying level so I basically removed the level argument so that the method enables flashlight but with the default level (I guess) which works.

(Tested with the flashlight shortcut in lockscreen).

I've attatched here the SystemUI patched. As the apk is bigger than 10MB I've added the apk into a zip archive and splitted in 8 parts but since Github doesn't allow to attach files with 00x extensions I've renamed each part adding the zip extension.

[SystemUI.zip.001.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860858/SystemUI.zip.001.zip)
[SystemUI.zip.002.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860859/SystemUI.zip.002.zip)
[SystemUI.zip.003.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860860/SystemUI.zip.003.zip)
[SystemUI.zip.004.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860861/SystemUI.zip.004.zip)
[SystemUI.zip.005.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860862/SystemUI.zip.005.zip)
[SystemUI.zip.006.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860863/SystemUI.zip.006.zip)
[SystemUI.zip.007.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860864/SystemUI.zip.007.zip)
[SystemUI.zip.008.zip](https://github.com/ananjaser1211/hadesRom_Reports/files/5860865/SystemUI.zip.008.zip)

**Comment by ananjaser1211** [comment]
This now affects S8/S8+ models, since fixing iris involved breaking the fix that made flash intensity controller work.
i indeed should have just disabled the flash level controller but it totally slipped my mind.

@lucf15 thanks for the fix (i know it is pretty late) will implement it in the next release.

**Comment by corsicanu** [comment]
> This now affects S8/S8+ models, since fixing iris involved breaking the fix that made flash intensity controller work.
> i indeed should have just disabled the flash level controller but it totally slipped my mind.
> 
> @lucf15 thanks for the fix (i know it is pretty late) will implement it in the next release.

Do not forget this is system wide and needs to be patched also in places like edge tools or more.

**Comment by ananjaser1211** [comment]
Hades V3.0 Has been released and addressed this issue, if the issue persists, please reopen with logs / details
